package com.jicl.entity;

public class dptInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dpt_info.dpt_id
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    private Integer dptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dpt_info.dpt_name
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    private String dptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dpt_info.dpt_tel
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    private Integer dptTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dpt_info.dpt_id
     *
     * @return the value of t_dpt_info.dpt_id
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    public Integer getDptId() {
        return dptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dpt_info.dpt_id
     *
     * @param dptId the value for t_dpt_info.dpt_id
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    public void setDptId(Integer dptId) {
        this.dptId = dptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dpt_info.dpt_name
     *
     * @return the value of t_dpt_info.dpt_name
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    public String getDptName() {
        return dptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dpt_info.dpt_name
     *
     * @param dptName the value for t_dpt_info.dpt_name
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    public void setDptName(String dptName) {
        this.dptName = dptName == null ? null : dptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dpt_info.dpt_tel
     *
     * @return the value of t_dpt_info.dpt_tel
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    public Integer getDptTel() {
        return dptTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dpt_info.dpt_tel
     *
     * @param dptTel the value for t_dpt_info.dpt_tel
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    public void setDptTel(Integer dptTel) {
        this.dptTel = dptTel;
    }
}