package com.jicl.entity;

import java.math.BigDecimal;
import java.util.Date;

public class empInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp_info.emp_id
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp_info.emp_name
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp_info.emp_gender
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    private String empGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp_info.emp_salary
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    private BigDecimal empSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp_info.emp_birthday
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    private Date empBirthday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp_info.emp_id
     *
     * @return the value of t_emp_info.emp_id
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp_info.emp_id
     *
     * @param empId the value for t_emp_info.emp_id
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp_info.emp_name
     *
     * @return the value of t_emp_info.emp_name
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp_info.emp_name
     *
     * @param empName the value for t_emp_info.emp_name
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp_info.emp_gender
     *
     * @return the value of t_emp_info.emp_gender
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    public String getEmpGender() {
        return empGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp_info.emp_gender
     *
     * @param empGender the value for t_emp_info.emp_gender
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    public void setEmpGender(String empGender) {
        this.empGender = empGender == null ? null : empGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp_info.emp_salary
     *
     * @return the value of t_emp_info.emp_salary
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    public BigDecimal getEmpSalary() {
        return empSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp_info.emp_salary
     *
     * @param empSalary the value for t_emp_info.emp_salary
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    public void setEmpSalary(BigDecimal empSalary) {
        this.empSalary = empSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp_info.emp_birthday
     *
     * @return the value of t_emp_info.emp_birthday
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    public Date getEmpBirthday() {
        return empBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp_info.emp_birthday
     *
     * @param empBirthday the value for t_emp_info.emp_birthday
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    public void setEmpBirthday(Date empBirthday) {
        this.empBirthday = empBirthday;
    }
}