package com.jicl.mapper;

import com.jicl.entity.dptInfo;
import com.jicl.entity.dptInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface dptInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dpt_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    long countByExample(dptInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dpt_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    int deleteByExample(dptInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dpt_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    int deleteByPrimaryKey(Integer dptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dpt_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    int insert(dptInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dpt_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    int insertSelective(dptInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dpt_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    List<dptInfo> selectByExample(dptInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dpt_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    dptInfo selectByPrimaryKey(Integer dptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dpt_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") dptInfo record, @Param("example") dptInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dpt_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    int updateByExample(@Param("record") dptInfo record, @Param("example") dptInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dpt_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    int updateByPrimaryKeySelective(dptInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dpt_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    int updateByPrimaryKey(dptInfo record);
}