package com.jicl.mapper;

import com.jicl.entity.empInfo;
import com.jicl.entity.empInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface empInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    long countByExample(empInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    int deleteByExample(empInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    int insert(empInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    int insertSelective(empInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    List<empInfo> selectByExample(empInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    empInfo selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") empInfo record, @Param("example") empInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    int updateByExample(@Param("record") empInfo record, @Param("example") empInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    int updateByPrimaryKeySelective(empInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_info
     *
     * @mbg.generated Tue Aug 20 22:36:56 CST 2019
     */
    int updateByPrimaryKey(empInfo record);
}